language: node_js
node_js:
  - "14"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - APPLICATION_PORT=5000  MONGO_CLOUD_URL_TEST=mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false REDIS_CLIENT_URL=redis://127.0.0.1:6379 DB_NAME=09072021-BlogApp-Test
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - nohup node app.js & 
  - sleep 10
  - npm run test